name: Build

on:
  push:
    branches:
      - main
    paths:
      - "Cargo.toml"
      - "meme_generator/**"
      - "meme_generator_cli/**"
      - "meme_generator_core/**"
      - "meme_generator_memes/**"
      - "meme_generator_py/**"
      - "meme_generator_server/**"
      - "meme_generator_utils/**"
      - "meme_options_derive/**"
    tags:
      - "v*"
  pull_request_target:
    paths:
      - "Cargo.toml"
      - "meme_generator/**"
      - "meme_generator_cli/**"
      - "meme_generator_core/**"
      - "meme_generator_memes/**"
      - "meme_generator_py/**"
      - "meme_generator_server/**"
      - "meme_generator_utils/**"
      - "meme_options_derive/**"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/build.yaml


  crates_io_publish:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.88.0
      - uses: swatinem/rust-cache@v2

      - name: Cargo login
        run: cargo login ${{ secrets.CRATES_IO_API_TOKEN }}

      - name: Cargo Publish
        run: |
          cargo publish --package meme_generator_memes
          cargo publish --package meme_generator

  pypi_publish:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/download-artifact@v4

      - name: Publish to PyPI
        uses: PyO3/maturin-action@v1
        env:
          MATURIN_PYPI_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        with:
          command: upload
          args: --non-interactive --skip-existing meme-generator-wheels-*/*

  node_publish:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4

      - name: Publish to npm
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - run: npm publish --access public meme-generator-node-*/*
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  release_draft:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: dawidd6/action-download-artifact@v11
        with:
          skip_unpack: true
      - uses: softprops/action-gh-release@v2
        with:
          name: ${{ github.ref }}
          draft: true
          files: |
            meme-generator-cli-*
